import { Bell, ChevronRight, KeyRound, LogOut, Menu, Settings, UserRound, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { useState } from 'react'
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom'
import { BrandMark } from '../components/ui/DataDisplay'
import { ThemeToggle } from '../components/ui/ThemeToggle'
import { useAuth } from '../hooks/useAuth'

const nav = [{ to: '/app/profile', label: 'Profile', icon: UserRound }, { to: '/app/settings', label: 'Profile settings', icon: Settings }, { to: '/app/change-password', label: 'Security', icon: KeyRound }]
export function DashboardLayout() {
  const [open, setOpen] = useState(false); const { user, logout } = useAuth(); const location = useLocation(); const current = nav.find((item) => location.pathname.startsWith(item.to))
  return <div className="app-canvas min-h-screen"><header className="glass fixed inset-x-0 top-0 z-40 flex h-16 items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><button className="focus-ring rounded p-2 lg:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu className="size-5" /></button><Link to="/app/profile"><BrandMark /></Link></div><div className="flex items-center gap-1"><ThemeToggle /><button className="focus-ring rounded-md p-2.5 text-slate-400 transition-colors hover:bg-white/5 hover:text-white" aria-label="Notifications"><Bell className="size-4" /></button><span className="ml-2 hidden text-right sm:block"><b className="block text-xs">{user?.fullName}</b><small className="text-slate-500">{user?.roles[0]}</small></span><img src={user?.profileImageUrl || `https://ui-avatars.com/api/?name=${encodeURIComponent(user?.fullName || 'Trader')}&background=21c997&color=07100d`} alt="" className="ml-2 size-9 rounded-full border border-white/10 object-cover" /></div></header>
    <aside className={`fixed inset-y-0 left-0 z-50 w-64 border-r border-white/[.07] bg-ink-900 p-4 pt-20 transition-transform lg:z-30 lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><button onClick={() => setOpen(false)} className="absolute right-3 top-3 rounded p-2 lg:hidden" aria-label="Close navigation"><X className="size-5" /></button><nav aria-label="Account navigation" className="space-y-1">{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => `focus-ring flex items-center gap-3 rounded-md px-3 py-3 text-sm font-semibold transition ${isActive ? 'bg-mint-400/10 text-mint-400' : 'text-slate-400 hover:bg-white/[.04] hover:text-white'}`}><Icon className="size-4" />{label}</NavLink>)}</nav><button onClick={() => void logout()} className="focus-ring absolute bottom-5 left-4 right-4 flex items-center gap-3 rounded-md px-3 py-3 text-sm font-semibold text-slate-400 hover:bg-coral-400/10 hover:text-coral-400"><LogOut className="size-4" />Sign out</button></aside>
    <AnimatePresence>{open && <motion.button initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-40 bg-black/60 lg:hidden" onClick={() => setOpen(false)} aria-label="Close navigation overlay" />}</AnimatePresence>
    <main className="min-h-screen px-4 pb-12 pt-24 sm:px-6 lg:ml-64 lg:px-10"><motion.div key={location.pathname} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .28 }} className="mx-auto max-w-6xl"><div className="mb-7 flex items-center gap-2 text-xs text-slate-500"><Link to="/app/profile" className="hover:text-white">Account</Link><ChevronRight className="size-3" /><span className="text-slate-300">{current?.label ?? 'Overview'}</span></div><Outlet /></motion.div></main>
    <footer className="border-t border-white/[.06] px-6 py-5 text-center text-xs text-slate-600 lg:ml-64">TradeWise AI · Secure account workspace</footer>
  </div>
}