import { ArrowRight, BarChart3, BrainCircuit, CheckCircle2, Menu, ShieldCheck, X } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { BrandMark } from '../components/ui/DataDisplay'
import { useDocumentTitle } from '../hooks/useDocumentTitle'

export function LandingPage() {
  useDocumentTitle('Trading intelligence'); const [menu, setMenu] = useState(false)
  return <div className="min-h-screen bg-ink-950"><header className="fixed inset-x-0 top-0 z-40 flex h-16 items-center justify-between border-b border-white/[.07] bg-ink-950/80 px-5 backdrop-blur-xl sm:px-8 lg:px-12"><BrandMark /><nav className="hidden items-center gap-7 md:flex"><a href="#capabilities" className="text-sm text-slate-400 hover:text-white">Capabilities</a><a href="#method" className="text-sm text-slate-400 hover:text-white">Method</a><Link to="/login" className="text-sm font-bold text-white">Sign in</Link><Link to="/register" className="rounded-md bg-mint-400 px-4 py-2.5 text-sm font-bold text-ink-950 hover:bg-mint-500">Start journaling</Link></nav><button className="focus-ring rounded p-2 md:hidden" onClick={() => setMenu((value) => !value)} aria-label="Toggle navigation">{menu ? <X /> : <Menu />}</button>{menu && <nav className="glass absolute left-4 right-4 top-18 rounded-lg p-3 md:hidden"><Link className="block rounded px-3 py-3 text-sm" to="/login">Sign in</Link><Link className="block rounded bg-mint-400 px-3 py-3 text-center text-sm font-bold text-ink-950" to="/register">Create account</Link></nav>}</header>
    <main><section className="relative flex min-h-[92svh] items-end overflow-hidden px-5 pb-14 pt-28 sm:px-8 lg:px-12 lg:pb-20"><img src="https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=2200&q=88" alt="Trading market data displayed across a professional workstation" className="absolute inset-0 h-full w-full object-cover object-center opacity-45" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#070a0f_0%,rgba(7,10,15,.88)_42%,rgba(7,10,15,.2)_100%)]" /><div className="grid-surface absolute inset-0 opacity-20" /><motion.div className="relative z-10 max-w-3xl" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}><span className="inline-flex items-center gap-2 rounded-full border border-mint-400/25 bg-ink-950/60 px-3 py-1.5 text-xs font-bold text-mint-400"><ShieldCheck className="size-3.5" />DECISIONS OVER NOISE</span><h1 className="mt-6 font-display text-5xl font-bold leading-[1.03] sm:text-6xl lg:text-7xl">TradeWise AI</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">A disciplined trading journal and portfolio analyzer that turns every position into measurable insight.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="focus-ring inline-flex items-center gap-2 rounded-md bg-mint-400 px-5 py-3.5 text-sm font-bold text-ink-950 hover:bg-mint-500">Build your trading record <ArrowRight className="size-4" /></Link><Link to="/login" className="focus-ring rounded-md border border-white/15 bg-black/30 px-5 py-3.5 text-sm font-bold backdrop-blur hover:bg-white/10">Open workspace</Link></div></motion.div></section>
      <section id="capabilities" className="border-y border-white/[.07] bg-ink-900 px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><span className="text-xs font-bold text-mint-400">YOUR OPERATING SYSTEM</span><h2 className="mt-3 max-w-md font-display text-3xl font-bold sm:text-4xl">One record for the full life of every trade.</h2></div><div className="grid gap-px overflow-hidden rounded-lg border border-white/[.07] bg-white/[.07] sm:grid-cols-3"><Feature icon={BarChart3} title="Portfolio truth" text="Track allocation, cash, exposure, and performance without spreadsheet drift." /><Feature icon={BrainCircuit} title="AI reflection" text="Surface repeatable strengths and costly behavioral patterns from your journal." /><Feature icon={CheckCircle2} title="Risk discipline" text="Review process quality alongside returns, drawdown, and consistency." /></div></div></section>
      <section id="method" className="px-5 py-14 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6"><p className="max-w-2xl font-display text-2xl font-bold">Your best trading edge is the quality of your feedback loop.</p><Link to="/register" className="inline-flex items-center gap-2 font-bold text-mint-400">Start building yours <ArrowRight className="size-4" /></Link></div></section></main>
    <footer className="border-t border-white/[.07] px-5 py-7 text-sm text-slate-500 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-2 sm:flex-row"><span>© 2026 TradeWise AI</span><span>Private by design. Deliberate by default.</span></div></footer>
  </div>
}
function Feature({ icon: Icon, title, text }: { icon: typeof BarChart3; title: string; text: string }) { return <article className="bg-ink-900 p-6"><Icon className="mb-12 size-5 text-mint-400" /><h3 className="font-display text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article> }