import { Clock3, Home, LockKeyhole, SearchX } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '../components/ui/Button'
import { BrandMark } from '../components/ui/DataDisplay'
import { useDocumentTitle } from '../hooks/useDocumentTitle'

function SystemPage({ code, title, description, icon: Icon, action = 'Return home', to = '/' }: { code: string; title: string; description: string; icon: typeof Home; action?: string; to?: string }) { useDocumentTitle(title); return <main className="app-canvas grid min-h-screen place-items-center px-5"><div className="absolute left-6 top-6"><BrandMark /></div><div className="max-w-md text-center"><span className="mx-auto grid size-16 place-items-center rounded-lg border border-white/10 bg-white/[.04] text-mint-400"><Icon className="size-7" /></span><p className="mt-7 text-xs font-bold text-mint-400">{code}</p><h1 className="mt-2 font-display text-4xl font-bold">{title}</h1><p className="mt-3 leading-7 text-slate-400">{description}</p><Link to={to} className="mt-7 inline-block"><Button icon={Home}>{action}</Button></Link></div></main> }
export function UnauthorizedPage() { return <SystemPage code="403 · ACCESS RESTRICTED" title="Not authorized" description="Your current role does not permit access to this workspace. Return to your account or contact an administrator." icon={LockKeyhole} action="Back to profile" to="/app/profile" /> }
export function SessionExpiredPage() { return <SystemPage code="SESSION ENDED" title="Your session expired" description="For your security, this session was closed. Sign in again to continue where you left off." icon={Clock3} action="Sign in again" to="/login" /> }
export function NotFoundPage() { return <SystemPage code="404 · OFF THE CHART" title="Page not found" description="The page you requested is not part of this workspace, or the address has changed." icon={SearchX} /> }