import { AlertCircle, Inbox, LoaderCircle, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import type { ReactNode } from 'react'
import { Button } from './Button'

export function Loader({ label = 'Loading' }: { label?: string }) { return <div role="status" className="flex min-h-48 flex-col items-center justify-center gap-3 text-slate-400"><LoaderCircle className="size-7 animate-spin text-mint-400" /><span className="text-sm">{label}</span></div> }
export function Spinner() { return <LoaderCircle className="size-4 animate-spin" aria-label="Loading" /> }
export function Skeleton({ className = '' }: { className?: string }) { return <div aria-hidden className={`animate-pulse rounded-md bg-white/[.06] ${className}`} /> }
export function Alert({ children, tone = 'error' }: { children: ReactNode; tone?: 'error' | 'info' | 'success' }) { const styles = tone === 'error' ? 'border-coral-400/30 bg-coral-400/10 text-red-200' : tone === 'success' ? 'border-mint-400/30 bg-mint-400/10 text-emerald-100' : 'border-sky-400/30 bg-sky-400/10 text-sky-100'; return <div role="alert" className={`flex gap-2 rounded-md border p-3 text-sm ${styles}`}><AlertCircle className="mt-0.5 size-4 shrink-0" />{children}</div> }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="flex min-h-56 flex-col items-center justify-center text-center"><Inbox className="mb-4 size-8 text-slate-600" /><h3 className="font-display font-bold">{title}</h3><p className="mt-1 max-w-sm text-sm text-slate-400">{description}</p></div> }
export function Modal({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) { return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.div role="dialog" aria-modal="true" aria-labelledby="modal-title" className="glass w-full max-w-md rounded-lg p-5" initial={{ scale: .96, y: 12 }} animate={{ scale: 1, y: 0 }} onMouseDown={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 id="modal-title" className="font-display text-lg font-bold">{title}</h2><button onClick={onClose} aria-label="Close dialog" className="focus-ring rounded p-2 text-slate-400 hover:bg-white/5 hover:text-white"><X className="size-4" /></button></div>{children}</motion.div></motion.div>}</AnimatePresence> }
export function ConfirmationDialog({ open, onClose, onConfirm, title, description }: { open: boolean; onClose: () => void; onConfirm: () => void; title: string; description: string }) { return <Modal open={open} onClose={onClose} title={title}><p className="mb-5 text-sm text-slate-400">{description}</p><div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="danger" onClick={onConfirm}>Confirm</Button></div></Modal> }